theme: jekyll-theme-cayman
title: Bruce Haydon's Repository
description: This GitHub repository contains various documents and source-code files relating to Cloud-Native application development and machine learning.
